### ISSUE TITLE
Please share Wifi manager type code for realtek Ameba WiFi module (RTL8195A) 

### ISSUE THREAD

**Issue by sw-tt-parasshah** [sychen/cpbl-parser#1]
I want to develop this: https://github.com/tzapu/WiFiManager

Please share Wifi manager type code for realtek Ameba WiFi module (RTL8195A) 

WiFi module (RTL8195A) has same support with arduino similar to ESP8266. If any one can help to make similar code for WiFi module (RTL8195A) then it will really help for me.

Board details: https://www.amebaiot.com/en/boards/
LED on/off sample code: https://www.amebaiot.com/en/ameba-arduino-web-server-status/

Thanks
Paras

**Comment by sychen** [comment]
I appreciate your enthusiasm for your project, but this is a repository about Taiwan professional  baseball.

I will close this issue.
Feel free to open new issues if you have something to share about this project itself.
Thank you.

**Comment by rogerable** [comment]
![image](https://user-images.githubusercontent.com/1728782/28450342-63c4ff26-6e19-11e7-9d47-9db1a09c5026.png)
